services:
  - type: web
    name: wellcomeai-backend
    env: python
    pythonVersion: 3.9.16
    buildCommand: |
      python3 -m venv venv
      . venv/bin/activate
      pip install --upgrade pip
      pip install -r server/requirements.txt
    startCommand: |
      cd server
      uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 10000
      - key: HOST_URL
        fromService:
          name: wellcomeai-backend
          type: web
          property: url