services:
  - type: web
    name: wellcomeai
    env: python
    region: frankfurt  # Выберите регион, наиболее близкий к вашим пользователям
    buildCommand: pip install -r server/requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker -w 4 -b 0.0.0.0:$PORT main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: HOST_URL
        fromService:
          type: web
          name: wellcomeai
          envVarKey: RENDER_EXTERNAL_URL
      - key: DATABASE_URL
        fromDatabase:
          name: wellcomeai-db
          property: connectionString

databases:
  - name: wellcomeai-db
    region: frankfurt
    plan: free  # Можно изменить на paid, если нужно больше ресурсов
